// ABOUTME: Auto-generated TypeScript types from the OpenAPI 3.1 spec.
// ABOUTME: Regenerate with: GENERATE_OPENAPI=1 go test -run TestOpenAPISpec ./internal/api/ && cd web && npm run generate-api
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the authenticated user's password */
        post: operations["change-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/invitations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get invitation details (public) */
        get: operations["get-invitation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/invitations/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an invitation and join the org */
        post: operations["accept-invitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in and receive auth cookies */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out and clear auth cookies */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's profile and org memberships */
        get: operations["get-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh token and issue a new access token */
        post: operations["refresh-token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user account */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search CVEs
         * @description Paginated CVE search with full-text search, facet filters, and keyset pagination.
         */
        get: operations["list-cves"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cves/{cve_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get CVE detail
         * @description Returns the canonical CVE row with affected packages, CPEs, and references.
         */
        get: operations["get-cve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cves/{cve_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get CVE source payloads
         * @description Returns per-source normalized payloads for a CVE, for cross-source comparison.
         */
        get: operations["get-cve-sources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AffectedCPEResponse: {
            cpe: string;
            cpe_normalized: string;
        };
        AffectedPackageResponse: {
            ecosystem: string;
            fixed?: string;
            introduced?: string;
            namespace?: string;
            package_name: string;
            range_type?: string;
        };
        CVEDetail: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CVEDetail.json
             */
            readonly $schema?: string;
            affected_cpes: components["schemas"]["AffectedCPEResponse"][] | null;
            affected_packages: components["schemas"]["AffectedPackageResponse"][] | null;
            cve_id: string;
            cvss_score_diverges: boolean;
            /** Format: double */
            cvss_v3_score?: number;
            cvss_v3_vector?: string;
            /** Format: double */
            cvss_v4_score?: number;
            cvss_v4_vector?: string;
            cwe_ids: string[] | null;
            date_first_seen: string;
            date_modified: string;
            date_published?: string;
            description_primary?: string;
            /** Format: double */
            epss_score?: number;
            exploit_available: boolean;
            in_cisa_kev: boolean;
            references: components["schemas"]["ReferenceResponse"][] | null;
            severity?: string;
            status?: string;
        };
        CVEItem: {
            cve_id: string;
            cvss_score_diverges: boolean;
            /** Format: double */
            cvss_v3_score?: number;
            /** Format: double */
            cvss_v4_score?: number;
            cwe_ids: string[] | null;
            date_first_seen: string;
            date_modified: string;
            date_published?: string;
            description_primary?: string;
            /** Format: double */
            epss_score?: number;
            exploit_available: boolean;
            in_cisa_kev: boolean;
            severity?: string;
            status?: string;
        };
        CVESourceResponse: {
            ingested_at: string;
            normalized_json: unknown;
            source_date_modified?: string;
            source_id?: string;
            source_name: string;
            source_url?: string;
        };
        ChangePasswordInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ChangePasswordInputBody.json
             */
            readonly $schema?: string;
            /** @description Current password */
            current_password: string;
            /** @description New password (min 16 characters) */
            new_password: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        GetCVESourcesBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetCVESourcesBody.json
             */
            readonly $schema?: string;
            sources: components["schemas"]["CVESourceResponse"][] | null;
        };
        GetInvitationOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetInvitationOutputBody.json
             */
            readonly $schema?: string;
            expires_at: string;
            org_name: string;
            role: string;
        };
        ListCVEsBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListCVEsBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["CVEItem"][] | null;
            next_cursor?: string;
        };
        LoginInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LoginInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: email
             * @description User email
             */
            email: string;
            /** @description Password */
            password: string;
        };
        MeOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/MeOutputBody.json
             */
            readonly $schema?: string;
            display_name: string;
            email: string;
            is_site_admin: boolean;
            orgs: components["schemas"]["OrgEntry"][] | null;
            user_id: string;
        };
        OrgEntry: {
            name: string;
            org_id: string;
            role: string;
        };
        ReferenceResponse: {
            tags: string[] | null;
            url: string;
        };
        RegisterInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RegisterInputBody.json
             */
            readonly $schema?: string;
            /** @description Display name (optional) */
            display_name?: string;
            /**
             * Format: email
             * @description User email address
             */
            email: string;
            /** @description Password (min 16 characters) */
            password: string;
        };
        RegisterOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RegisterOutputBody.json
             */
            readonly $schema?: string;
            org_id?: string;
            user_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description Access token cookie */
                access_token?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-invitation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invitation token */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetInvitationOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "accept-invitation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invitation token */
                token: string;
            };
            cookie?: {
                /** @description Access token cookie */
                access_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description Refresh token cookie */
                refresh_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description Access token cookie */
                access_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description Refresh token cookie */
                refresh_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-cves": {
        parameters: {
            query?: {
                /** @description Full-text search query (supports quoted phrases and negation) */
                q?: string;
                /** @description Filter by severity: critical, high, medium, low, unknown */
                severity?: string[] | null;
                /** @description Filter CVEs modified on or after this date (ISO 8601); empty = no filter */
                date_from?: string;
                /** @description Filter CVEs modified on or before this date (ISO 8601); empty = no filter */
                date_to?: string;
                /** @description Filter by CWE ID (e.g. CWE-79); empty = no filter */
                cwe_id?: string;
                /** @description Filter by affected package ecosystem; empty = no filter */
                ecosystem?: string;
                /** @description Filter by affected package name (requires ecosystem); empty = no filter */
                package_name?: string;
                /** @description Filter by CISA KEV status: 'true', 'false', or empty for no filter */
                in_cisa_kev?: string;
                /** @description Filter by exploit availability: 'true', 'false', or empty for no filter */
                exploit_available?: string;
                /** @description Opaque pagination cursor returned in the previous response */
                cursor?: string;
                /** @description Page size (max 100) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCVEsBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-cve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CVE identifier (e.g. CVE-2024-12345) */
                cve_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CVEDetail"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-cve-sources": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CVE identifier */
                cve_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCVESourcesBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
